/* automatically generated by rust-bindgen 0.57.0 */

extern "C" {
    pub fn OptickAPI_RegisterThread(
        inThreadName: *const ::std::os::raw::c_char,
        inThreadNameLength: u16,
    );
}
extern "C" {
    pub fn OptickAPI_CreateEventDescription(
        inFunctionName: *const ::std::os::raw::c_char,
        inFunctionLength: u16,
        inFileName: *const ::std::os::raw::c_char,
        inFileNameLenght: u16,
        inFileLine: u32,
    ) -> u64;
}
extern "C" {
    pub fn OptickAPI_PushEvent(inEventDescription: u64) -> u64;
}
extern "C" {
    pub fn OptickAPI_PopEvent(inEventData: u64);
}
extern "C" {
    pub fn OptickAPI_NextFrame();
}
extern "C" {
    pub fn OptickAPI_StartCapture();
}
extern "C" {
    pub fn OptickAPI_StopCapture(inFileName: *const ::std::os::raw::c_char, inFileNameLength: u16);
}
extern "C" {
    pub fn OptickAPI_AttachTag_String(
        inEventDescription: u64,
        inValue: *const ::std::os::raw::c_char,
        intValueLength: u16,
    );
}
extern "C" {
    pub fn OptickAPI_AttachTag_Int32(inEventDescription: u64, inValue: ::std::os::raw::c_int);
}
extern "C" {
    pub fn OptickAPI_AttachTag_Float(inEventDescription: u64, inValue: f32);
}
extern "C" {
    pub fn OptickAPI_AttachTag_UInt32(inEventDescription: u64, inValue: u32);
}
extern "C" {
    pub fn OptickAPI_AttachTag_UInt64(inEventDescription: u64, inValue: u64);
}
extern "C" {
    pub fn OptickAPI_AttachTag_Point(inEventDescription: u64, x: f32, y: f32, z: f32);
}
